"use strict";
exports.__esModule = true;
var AutoCiudad_1 = require("./AutoCiudad");
var AutoDeportivo_1 = require("./AutoDeportivo");
var Camioneta_1 = require("./Camioneta");
var autoCiudad = new AutoCiudad_1["default"]('Ford', 'Fiesta', 1999, 'ABC456', 190000);
autoCiudad.encenderApagar();
autoCiudad.frenar();
autoCiudad.acelerar();
autoCiudad.acelerar();
autoCiudad.frenar();
autoCiudad.imprimirDatos();
console.log(' ');
var autoDeportivo = new AutoDeportivo_1["default"]('Subaru', 'G-200', 2010, 'GE435JI', 450000);
autoDeportivo.encenderApagar();
autoDeportivo.acelerar();
autoDeportivo.acelerar();
autoDeportivo.acelerar();
autoDeportivo.frenar();
autoDeportivo.getEstadoPloteado();
autoDeportivo.imprimirDatos();
console.log(' ');
var miCamioneta = new Camioneta_1["default"]('Toyota', 'Hilux', 2017, 'AB201HD', 320000);
miCamioneta.encenderApagar();
miCamioneta.acelerar();
miCamioneta.acelerar();
miCamioneta.frenar();
miCamioneta.descargar();
miCamioneta.cargar();
miCamioneta.cargar();
miCamioneta.cargar();
miCamioneta.getEstadoCarga();
miCamioneta.imprimirDatos();
